### ISSUE TITLE
Consider registration of ResponseTaggers by convention

### ISSUE THREAD

**Issue by bdunogier** [ezsystems/ezplatform-http-cache#6]
ResponseTaggers are very simple, and their services declarations are very similar.

Most of them will only receive other response taggers as arguments. The name of the tagger should be easy to determine based on the name of the parameters:

```yaml
    ezplatform.view_cache.response_tagger.location_value_view:
        class: EzSystems\PlatformHttpCacheBundle\ResponseTagger\Delegator\LocationValueViewTagger
        arguments: ['@ezplatform.view_cache.response_tagger.location']
        tags:
            - {name: ezplatform.cache_response_tagger}
```

```php
class LocationValueViewTagger implements ResponseTagger
{
    /**
     * @var \EzSystems\PlatformHttpCacheBundle\ResponseTagger\ResponseTagger
     */
    private $locationTagger;

    public function __construct(ResponseTagger $locationTagger)
    {
        $this->locationTagger = $locationTagger;
    }
```

Other examples are `$dispatcherTagger`, `$contentInfoTagger`... the name of the tagger can easily be mapped from the name of the parameter: `contentInfoTagger` => `ezplatform.view_cache.response_tagger.content_info`.

Maybe a container parameter can be added so that any namespace can be added to the list of Convention paths ?

```yaml
ezplatform_http_cache:
  response_taggers:
    namespaces:
      - EzSystems\PlatformHttpCacheBundle\ResponseTagger\Value
      - EzSystems\PlatformHttpCacheBundle\ResponseTagger\Delegator
```
